### ISSUE TITLE
Demo app fails to build due to missing XHRInstrumentation export

### ISSUE THREAD

**Issue by nextrevision** [grafana/faro-web-sdk#441]
## Description

The demo app fails to build in the docker image step with the following error:

```
faro-web-sdk/demo $ docker compose --profile demo up

...snip...

64.03 "XHRInstrumentation" is not exported by "../experimental/instrumentation-xhr/dist/esm/index.js", imported by "src/client/faro/initialize.ts".
64.03 file: /usr/app/demo/src/client/faro/initialize.ts:3:9
64.03 1: import { createRoutesFromChildren, matchRoutes, Routes, useLocation, useNavigationType } from 'react-router-dom';
64.03 2:
64.03 3: import { XHRInstrumentation } from '@grafana/faro-instrumentation-xhr';
64.03             ^
64.03 4: import {
64.03 5:   initializeFaro as coreInit,
64.03 error during build:
64.03 RollupError: "XHRInstrumentation" is not exported by "../experimental/instrumentation-xhr/dist/esm/index.js", imported by "src/client/faro/initialize.ts".
64.03     at error (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
64.03     at Module.error (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
64.03     at Module.traceVariable (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
64.03     at ModuleScope.findVariable (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
64.03     at FunctionScope.findVariable (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
64.03     at ChildScope.findVariable (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
64.03     at Identifier.bind (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
64.03     at NewExpression.bind (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
64.03     at ArrayExpression.bind (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
64.03     at Property.bind (file:///usr/app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
64.03 ERROR: "build:client" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
64.04
64.04
64.04
64.04  >  Lerna (powered by Nx)   Running target build for 7 projects failed
64.04
64.04    Failed tasks:
64.04
64.04    - @grafana/faro-demo:build
64.04
64.06 error Command failed with exit code 1.
64.06 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```

I believe it's related to https://github.com/grafana/faro-web-sdk/commit/cd8b0c48cf39d832234d910cae7c2e596330510f. Switching to the commit before this (`git checkout 81cc1a9dfcf2b0b8596f47f71416f698529c285c`), I was able to get a successful build.

I also had to apply the fix mentioned in #440 to get to this point. Seems unlikely to be related, but it very well could be.

## Steps to reproduce

1. Clone a fresh version of the repo.
2. Change to the demo dir.
3. Remove any existing docker image builds: `docker rmi faro-web-sdk-demo`
4. Build via the recommended command: `docker compose --profile demo up`

## Expected behavior

The build succeeds and the demo app is created.

## Environment

- **SDK version:** c6d5cd070b441699850763af34f75ea219a5c0a9 (main)
- **OS:** MacOS

### Docker Version

```
$ docker version
Client:
 Version:           24.0.2-rd
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        e63f5fa
 Built:             Fri May 26 16:39:47 2023
 OS/Arch:           darwin/amd64
 Context:           default

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by codecapitano** [comment]
Hi @nextrevision and thanks for reporting!

This was caused by a leftover where we tested the experimental instrumentation but did not install them (add as a dependency to package.json).

Because the instrumentation is experimental, we removed it.

Cheers and thanks, 
Marco
