### ISSUE TITLE
Session Manager: guard against ciruclar references when stringifying a session

### ISSUE THREAD

**Issue by codecapitano** [grafana/faro-web-sdk#587]
## Description
A [user reported a `Maximum call stack size exceeded` exception ](https://grafana.slack.com/archives/C048UH68BM5/p1715155694123489) in Faro.

A "Maximum call stack size exceeded"  during JSON serialisation happens when an object contains circular references.
Circular references happen when an object references itself directly or through one of its child objects.

Example for a circular reference.
```js
const x = {};
const y = { x };
x.y = y
```

## Proposed solution
To handle circular references, you can use a custom replacer function as the second argument to JSON.stringify(). This function can check for circular references and either replace them with something JSON can serialize (like null or a special marker) or omit them from the resulting JSON.

## Context
![image](https://github.com/grafana/faro-web-sdk/assets/47627413/d801ff06-1118-4865-a591-0296009fd456)

**Comment by damusnet** [comment]
We are encountering the same issue. Raw, un-minified stack trace:

```
RangeError: Maximum call stack size exceeded.
  at stringify([native code])
  at VolatileSessionsManager.storeUserSession(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:20:28)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:41:1)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
  at <object>.add(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:15:1)
  at setSession(./node_modules/@grafana/faro-core/dist/esm/api/meta/initialize.js:22:1)
  at <anonymous>(./node_modules/@grafana/faro-web-sdk/dist/esm/instrumentations/session/sessionManager/VolatileSessionManager.js:42:21)
  at forEach([native code])
  at notifyListeners(./node_modules/@grafana/faro-core/dist/esm/metas/initialize.js:9:1)
```

![Image](https://github.com/user-attachments/assets/a0be81a1-14a1-4fc3-aed3-4348bf7ff726)
