### ISSUE TITLE
Unhandled Promise rejection: Failed to fetch

### ISSUE THREAD

**Issue by darktasevski** [grafana/faro-web-sdk#683]
## Description

If I have two or more Faro instances with `isolate` set to `true` once they load on the page, I start seeing a lot of Faro requests, slowing down the application to a halt. It looks like some retry loop is triggered but I couldn't pinpoint the exact issue. I'm working on microfrontends, and we tried initializing the Faro instance per MF, but as soon as the second MF is loaded and it's Faro initialized, the application becomes unusable.

Here's an example of the configuration used to set the MFE Faro instance:

```ts
initializeFaro({
				url: collectorUrl,
				app: {
					name: appName,
					version: __APP_VERSION__,
					environment: deploymentEnv,
				},
				isolate: true,
				sessionTracking: {
					generateSessionId: () => {
						return getSessionId(mfeSessionIdSessionStorageKey);
					},
				},
				instrumentations: [
					// Mandatory, omits default instrumentations otherwise.
					...getWebInstrumentations(),
					// Tracing package to get end-to-end visibility for HTTP requests.
					new TracingInstrumentation(),
					// React integration for React applications.
					new ReactIntegration(),
				],
			});
```
For Angular MFE we have something similar but without the `ReactIntegration`.

## Steps to reproduce

1. Add Faro to the MF project
2. Add Faro to another MF projects that's loaded by the first one
3. Start the first project and load the page where the second MF is visible
4. Observe that in dev tools network log we have a lot of Faro requests triggered (around 500requests per minute)

## Expected behavior

Host application reports it's own metrics, remote application reports it's own, without entering the loop and slowing down the whole application.

## Actual behavior

```

{
  "meta": {
    "sdk": {
      "version": "1.8.2"
    },
    "app": {
      "name": "EPMS UI",
      "version": "c39cc4e8d5",
      "environment": "development"
    },
    "view": {
      "name": "default"
    },
    "browser": {
      "name": "Safari",
      "version": "16.0",
      "os": "Mac OS 10.15.7",
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15",
      "language": "en-US",
      "mobile": false,
      "brands": [],
      "viewportWidth": "820",
      "viewportHeight": "1180"
    },
    "page": {
      "url": "http://localhost:<masked>/#/login",
      "id": "/login"
    },
    "session": {
      "id": "51el0z28jx8"
    }
  },
  "logs": [
    {
      "message": "Unhandled Promise rejection: Failed to fetch ; Zone: <root> ; Task: null ; Value: TypeError: Failed to fetch TypeError: Failed to fetch\n    at n (chrome-extension://mdnleldcmiljblolnjhpnblkcekpdkpa/page-scripts/ajaxRequestInterceptor.ps.js:1:12673)\n    at fetch (chrome-extension://mdnleldcmiljblolnjhpnblkcekpdkpa/page-scripts/ajaxRequestInterceptor.ps.js:1:13726)",
      "level": "error",
      "context": {},
      "timestamp": "2024-09-18T15:44:32.293Z"
    },
    {
      "message": "Faro\n @grafana/faro-web-sdk:transport-fetch\n Failed sending payload to the receiver\n [object Object] TypeError: Failed to fetch",
      "level": "error",
      "context": {},
      "timestamp": "2024-09-18T15:44:32.294Z"
    }
  ]
}
```

## Environment

- **SDK version:** 1.8.2
- **SDK instrumentations:** getWebInstrumentations, TracingInstrumentation
- **Device type:** desktop
- **Device name:** desktop
- **OS:** Windows, OSX
- **Browser:** any

**Comment by codecapitano** [comment]
Hi @darktasevski 

Do the Faro instances send data to different collector endpoints?
If yes, the different Faro instances would start tracking each other.

By default a Faro instance excludes its own collector endpoint but doesn't know about the other instances.
If those instances have different endpoints they'll be tracked.

Solution is to [ignore the collector endpoints](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/exclude-endpoints/) of the other instances.

Relate issue: https://github.com/grafana/faro-web-sdk/issues/671#issuecomment-2337854787

Does this solve your issue?

Offtopic:  
I see that you're on an older Faro version (1.8.2).
I recommend updating Faro to the current version.
